// THIS FILE IS AUTOMATICALLY GENERATED AS A LOCAL BACKUP FALLBACK FOR PLATFORM REDIRECTS
export const fallbackUsers = [
  {
    "username": "AHMAD",
    "email": "ahmad@alwaleed-factory.com",
    "id": "AHMAD",
    "password": "2424",
    "permissions": {
      "moduleAccess": {
        "sales": {
          "viewAccess": "all",
          "add": true,
          "deleteAccess": "all",
          "print": true,
          "exportExcel": true,
          "deleteSensitive": true,
          "exportPdf": true,
          "delete": true,
          "enabled": true,
          "viewCosts": true,
          "approve": true,
          "view": true,
          "edit": true,
          "editAccess": "all"
        },
        "reports": {
          "editAccess": "all",
          "edit": true,
          "approve": true,
          "view": true,
          "enabled": true,
          "viewCosts": true,
          "exportPdf": true,
          "delete": true,
          "print": true,
          "exportExcel": true,
          "deleteSensitive": true,
          "deleteAccess": "all",
          "add": true,
          "viewAccess": "all"
        },
        "notifications": {
          "viewAccess": "all",
          "editAccess": "all",
          "enabled": true
        },
        "hr": {
          "delete": true,
          "exportPdf": true,
          "exportExcel": true,
          "deleteSensitive": true,
          "print": true,
          "add": true,
          "deleteAccess": "all",
          "viewAccess": "all",
          "edit": true,
          "editAccess": "all",
          "view": true,
          "approve": true,
          "enabled": true,
          "viewCosts": true
        },
        "procurement": {
          "enabled": true,
          "viewCosts": true,
          "approve": true,
          "view": true,
          "editAccess": "all",
          "edit": true,
          "viewAccess": "all",
          "add": true,
          "deleteAccess": "all",
          "print": true,
          "exportExcel": true,
          "deleteSensitive": true,
          "exportPdf": true,
          "delete": true
        },
        "production": {
          "editAccess": "all",
          "edit": true,
          "view": true,
          "approve": true,
          "enabled": true,
          "viewCosts": true,
          "delete": true,
          "exportPdf": true,
          "exportExcel": true,
          "deleteSensitive": true,
          "print": true,
          "add": true,
          "deleteAccess": "all",
          "viewAccess": "all"
        },
        "finance": {
          "enabled": true,
          "viewCosts": true,
          "editAccess": "all",
          "edit": true,
          "view": true,
          "approve": true,
          "add": true,
          "deleteAccess": "all",
          "viewAccess": "all",
          "delete": true,
          "exportPdf": true,
          "deleteSensitive": true,
          "exportExcel": true,
          "print": true
        },
        "settings": {
          "approve": false,
          "print": false,
          "view": true,
          "exportExcel": false,
          "deleteSensitive": false,
          "edit": false,
          "exportPdf": false,
          "delete": false,
          "enabled": false,
          "viewCosts": false,
          "add": false
        }
      },
      "scopes": {
        "global": "all"
      },
      "advanced": {
        "settings": {
          "audit": {
            "delete_audit": false,
            "view_audit": false
          },
          "users": {
            "add_user": false,
            "edit_user": false,
            "view_users": false,
            "manage_permissions": false
          },
          "general": {
            "view_settings": false,
            "edit_settings": false,
            "database_backup": false
          }
        },
        "finance": {
          "supplier_invoices": {
            "edit_invoice": "all",
            "add_invoice": "all",
            "approve_invoice": "all",
            "view_portal": "all"
          },
          "customer_invoices": {
            "export_all": "all",
            "view_portal": "all",
            "add_invoice": "all",
            "preview_invoice": "all",
            "approve_invoice": "all",
            "edit_invoice": "all"
          },
          "zakat_tax": {
            "view_zakat_tax": "all",
            "register_tax_payment": "all",
            "export_zakat_tax": "all"
          },
          "zatca": {
            "edit_zatca": "all",
            "view_zatca": "all"
          },
          "revenues": {
            "edit_revenues": "all",
            "view_revenues": "all"
          },
          "journal": {
            "add_entry": "all",
            "edit_entry": "all",
            "print_entry": "all",
            "approve_entry": "all",
            "view_projects": "all",
            "upload_attachment": "all",
            "view_entries": "all",
            "submit_approval": "all"
          },
          "expenses": {
            "view_expenses": "all",
            "edit_expenses": "all"
          },
          "cash_bank": {
            "view_portal": "all",
            "manage_cash_boxes": "all"
          },
          "payroll": {
            "audit_payroll_edit": "all",
            "audit_payroll_view": "all",
            "edit_payroll": "all",
            "revert_to_draft": "all",
            "view_payroll": "all"
          },
          "dashboard": {
            "view_dashboard": "all",
            "edit_dashboard": "all"
          },
          "reports": {
            "export_reports": "all",
            "view_reports": "all"
          }
        },
        "hr": {
          "dashboard": {
            "view_total_emp": "all",
            "view_attendance": "all",
            "view_expiries": "all",
            "view_dashboard": "all",
            "view_active_emp": "all",
            "view_total_deductions": "all",
            "view_leave_emp": "all",
            "view_total_salaries": "all",
            "view_total_loans": "all"
          },
          "self_service": {
            "view_attachments": "all",
            "reply_inquiry": "all",
            "forward_inquiry": "all",
            "close_inquiry": "all",
            "print_inquiry": "all",
            "view_inquiries": "all",
            "delete_inquiry": "all"
          },
          "deductions": {
            "edit_deduction": "all",
            "add_deduction": "all",
            "approve_deduction": "all",
            "view_deductions": "all"
          },
          "performance": {
            "add_perf": "all",
            "approve_perf": "all",
            "view_perf": "all"
          },
          "employees": {
            "edit_salary": "all",
            "delete_emp": "all",
            "add_emp": "all",
            "edit_emp": "all",
            "qiwa_muqeem": "all",
            "view_emp": "all",
            "manage_files": "all",
            "disable_emp": "all",
            "view_salary": "all"
          },
          "payroll": {
            "print_payroll": "all",
            "create_payroll": "all",
            "view_payroll": "all",
            "approve_payroll": "all",
            "revert_payroll_draft": "all",
            "post_mudad": "all",
            "edit_components": "all"
          },
          "leaves": {
            "approve_leave": "all",
            "delete_leave": "all",
            "edit_balances": "all",
            "view_balances": "all",
            "edit_leave": "all",
            "add_leave": "all"
          },
          "letters": {
            "create_letter": "all",
            "view_letters": "all",
            "edit_letter_template": "all"
          }
        },
        "procurement": {
          "suppliers": {
            "manage_suppliers": "all",
            "view_suppliers": "all",
            "issue_rfq": "all"
          },
          "finance_approval": {
            "approve_finance_po": "all",
            "reject_finance_po": "all",
            "view_finance_po": "all",
            "undo_po": "all",
            "delete_finance_po": "all"
          },
          "materials": {
            "view_materials": "all",
            "inventory_audit": "all",
            "manage_materials": "all",
            "adjust_qty": "all"
          },
          "dashboard": {
            "view_dashboard": "all"
          },
          "daily_purchases": {
            "view_daily_purchases": "all",
            "confirm_finance_daily": "all",
            "add_daily_purchase": "all",
            "delete_daily_purchase": "all"
          },
          "requests": {
            "add_request": "all",
            "approve_request": "all",
            "send_pricing": "all",
            "view_requests": "all"
          },
          "approved_po": {
            "receive_items": "all",
            "view_pos": "all",
            "cancel_po": "all"
          },
          "items": {
            "view_items": "all",
            "manage_items": "all",
            "approve_item": "all"
          }
        },
        "notifications": {
          "general": {
            "view_finance": "all",
            "view_purchasing": "all",
            "view_public": "all",
            "view_private": "all",
            "view_sales": "all",
            "view_all": "all",
            "view_hr": "all",
            "view_production": "all"
          }
        },
        "production": {
          "dashboard": {
            "view_dashboard": "all"
          },
          "received": {
            "accept_reject": "all",
            "view_cost_pricing": "all",
            "create_order": "all",
            "view_received": "all"
          },
          "installation": {
            "complete_install": "all",
            "view_install": "all",
            "schedule_install": "all"
          },
          "projects": {
            "view_projects": "all",
            "mark_ready": "all",
            "mark_complete_no_auth": "all",
            "manage_stages": "all"
          },
          "daily_followup": {
            "delete_daily_followup": "all",
            "manage_daily_followup": "all",
            "view_daily_followup": "all",
            "edit_daily_followup": "all"
          },
          "orders": {
            "approve_orders": "all",
            "manage_orders": "all",
            "view_orders": "all"
          }
        },
        "dashboard": {
          "metrics": {
            "filter_date": "all",
            "view_hr": "all",
            "view_production": "all",
            "view_main": "all",
            "view_logs": "all",
            "view_financial": "all",
            "view_inventory": "all",
            "view_alerts": "all",
            "view_procurement": "all",
            "view_payroll": "all",
            "export_metrics": "all",
            "view_sales": "all"
          },
          "quick_shortcuts": {
            "view_procurement_shortcuts": "all",
            "view_main_shortcuts": "all",
            "view_production_shortcuts": "all"
          }
        },
        "sales": {
          "letters": {
            "edit_letter_template": "all",
            "add_letter": "all",
            "view_letters": "all",
            "send_letter": "all"
          },
          "clients": {
            "view_clients": "all",
            "delete_client": "all",
            "import_clients": "all",
            "add_client": "all",
            "edit_client": "all"
          },
          "reports": {
            "export_reports": "all",
            "view_reports": "all"
          },
          "reps": {
            "approve_comission": "all",
            "view_reps": "all",
            "manage_targets": "all"
          },
          "dashboard": {
            "view_dashboard": "all",
            "view_financial": "all"
          },
          "prod_orders": {
            "resend_prod": "all",
            "view_prod_orders": "all",
            "delete_prod_order": "all"
          },
          "pricing_study": {
            "edit_pricing_study": "all",
            "view_pricing_study": "all"
          },
          "collection": {
            "edit_plan": "all",
            "approve_payment": "all",
            "unapprove_payment": "all",
            "add_plan": "all",
            "delete_payment": "all",
            "view_collection": "all",
            "add_payment": "all"
          },
          "quotations": {
            "edit_quote": "all",
            "send_production": "all",
            "add_quote": "all",
            "approve_quote": "all",
            "delete_quote": "all",
            "view_quotes": "all",
            "unapprove_quote": "all",
            "delete_approved_quote": "all"
          }
        }
      }
    },
    "jobTitle": "نائب رئيس مجلس الادارة",
    "role": "General Admin Director",
    "empId": "EMP-4940"
  },
  {
    "username": "FERAS24",
    "email": "feras24@alwaleed-factory.com",
    "id": "FERAS24",
    "deviceLockEnabled": true,
    "pendingDeviceApprovalId": "",
    "pendingDeviceApprovalName": "",
    "boundDeviceId": "DEV-88nusni4cwi-mrnabsem",
    "permissions": {
      "advanced": {
        "sales": {
          "collection": {
            "unapprove_payment": "all",
            "edit_plan": "all",
            "approve_payment": "all",
            "add_plan": "all",
            "delete_payment": "all",
            "add_payment": "all",
            "view_collection": "all",
            "delete_confirmed_collection": "all"
          },
          "pricing_study": {
            "edit_pricing_study": "all",
            "view_pricing_study": "all"
          },
          "prod_orders": {
            "view_prod_orders": "all",
            "delete_prod_order": "all",
            "resend_prod": "all"
          },
          "quotations": {
            "unapprove_quote": "all",
            "delete_approved_quote": "all",
            "delete_quote": "all",
            "view_quotes": "all",
            "approve_quote": "all",
            "add_quote": "all",
            "edit_quote": "all",
            "send_production": "all"
          },
          "letters": {
            "edit_letter_template": "all",
            "add_letter": "all",
            "view_letters": "all",
            "send_letter": "all"
          },
          "clients": {
            "view_clients": "all",
            "import_clients": "all",
            "delete_client": "all",
            "add_client": "all",
            "edit_client": "all"
          },
          "reps": {
            "approve_comission": "all",
            "view_reps": "all",
            "manage_targets": "all"
          },
          "dashboard": {
            "view_dashboard": "all",
            "view_financial": "all"
          },
          "reports": {
            "export_reports": "all",
            "view_reports": "all"
          }
        },
        "dashboard": {
          "quick_shortcuts": {
            "view_production_shortcuts": "all",
            "view_main_shortcuts": "all",
            "view_procurement_shortcuts": "all"
          },
          "metrics": {
            "view_main": "all",
            "view_logs": "all",
            "view_production": "all",
            "view_hr": "all",
            "filter_date": "all",
            "view_sales": "all",
            "export_metrics": "all",
            "view_payroll": "all",
            "view_alerts": "all",
            "view_procurement": "all",
            "view_inventory": "all",
            "view_financial": "all"
          }
        },
        "hr": {
          "leaves": {
            "approve_leave": "all",
            "delete_leave": "all",
            "edit_leave": "all",
            "view_balances": "all",
            "edit_balances": "all",
            "add_leave": "all"
          },
          "payroll": {
            "view_payroll": "all",
            "create_payroll": "all",
            "print_payroll": "all",
            "edit_components": "all",
            "post_mudad": "all",
            "revert_payroll_draft": "all",
            "approve_payroll": "all"
          },
          "letters": {
            "edit_letter_template": "all",
            "view_letters": "all",
            "create_letter": "all"
          },
          "dashboard": {
            "view_total_loans": "all",
            "view_total_salaries": "all",
            "view_total_deductions": "all",
            "view_leave_emp": "all",
            "view_dashboard": "all",
            "view_active_emp": "all",
            "view_total_emp": "all",
            "view_expiries": "all",
            "view_attendance": "all"
          },
          "self_service": {
            "print_inquiry": "all",
            "delete_inquiry": "all",
            "view_inquiries": "all",
            "forward_inquiry": "all",
            "reply_inquiry": "all",
            "view_attachments": "all",
            "close_inquiry": "all"
          },
          "deductions": {
            "edit_deduction": "all",
            "view_deductions": "all",
            "add_deduction": "all",
            "approve_deduction": "all"
          },
          "employees": {
            "delete_emp": "all",
            "add_emp": "all",
            "edit_salary": "all",
            "edit_emp": "all",
            "view_emp": "all",
            "qiwa_muqeem": "all",
            "view_salary": "all",
            "disable_emp": "all",
            "manage_files": "all"
          },
          "performance": {
            "view_perf": "all",
            "add_perf": "all",
            "approve_perf": "all"
          }
        },
        "procurement": {
          "dashboard": {
            "view_dashboard": "all"
          },
          "materials": {
            "inventory_audit": "all",
            "view_materials": "all",
            "manage_materials": "all",
            "adjust_qty": "all"
          },
          "approved_po": {
            "cancel_po": "all",
            "view_pos": "all",
            "receive_items": "all"
          },
          "daily_purchases": {
            "delete_daily_purchase": "all",
            "view_daily_purchases": "all",
            "confirm_finance_daily": "all",
            "add_daily_purchase": "all"
          },
          "requests": {
            "view_requests": "all",
            "send_pricing": "all",
            "add_request": "all",
            "approve_request": "all"
          },
          "items": {
            "view_items": "all",
            "manage_items": "all",
            "approve_item": "all"
          },
          "finance_approval": {
            "undo_po": "all",
            "view_finance_po": "all",
            "approve_finance_po": "all",
            "reject_finance_po": "all",
            "delete_finance_po": "all"
          },
          "suppliers": {
            "manage_suppliers": "all",
            "issue_rfq": "all",
            "view_suppliers": "all"
          }
        },
        "production": {
          "projects": {
            "view_projects": "all",
            "mark_ready": "all",
            "mark_complete_no_auth": "all",
            "manage_stages": "all"
          },
          "installation": {
            "schedule_install": "all",
            "complete_install": "all",
            "view_install": "all"
          },
          "received": {
            "accept_reject": "all",
            "view_cost_pricing": "all",
            "create_order": "all",
            "view_received": "all"
          },
          "dashboard": {
            "view_dashboard": "all"
          },
          "orders": {
            "view_orders": "all",
            "manage_orders": "all",
            "approve_orders": "all"
          },
          "daily_followup": {
            "edit_daily_followup": "all",
            "manage_daily_followup": "all",
            "view_daily_followup": "all",
            "delete_daily_followup": "all"
          }
        },
        "notifications": {
          "general": {
            "view_hr": "all",
            "view_production": "all",
            "view_sales": "all",
            "view_all": "all",
            "view_public": "all",
            "view_private": "all",
            "view_finance": "all",
            "view_purchasing": "all"
          }
        },
        "settings": {
          "users": {
            "add_user": "all",
            "edit_user": "all",
            "view_users": "all",
            "manage_permissions": "all"
          },
          "audit": {
            "delete_audit": "all",
            "view_audit": "all"
          },
          "general": {
            "database_backup": "all",
            "edit_settings": "all",
            "view_settings": "all"
          }
        },
        "finance": {
          "zakat_tax": {
            "view_zakat_tax": "all",
            "register_tax_payment": "all",
            "export_zakat_tax": "all"
          },
          "customer_invoices": {
            "zatca_validate": "all",
            "upload_attachment": "all",
            "view_log": "all",
            "save_draft": "all",
            "register_unapproved_payment": "all",
            "create_from_quote": "all",
            "delete_approved_attachment": "all",
            "delete_payment": "all",
            "edit_draft": "all",
            "print_cancelled": "all",
            "edit_company_data": "all",
            "view_qr": "all",
            "send_approval": "all",
            "view_details": "all",
            "edit_payment": "all",
            "search_invoices": "all",
            "export_approved": "all",
            "edit_vat": "all",
            "cancel_invoice": "all",
            "open_add_modal": "all",
            "edit_invoice": "all",
            "unapprove_issued": "all",
            "approve_invoice": "all",
            "use_filters": "all",
            "edit_paid_amount": "all",
            "delete_unapproved": "all",
            "delete_draft": "all",
            "print_invoice": "all",
            "edit_approved": "all",
            "zatca_resend": "all",
            "register_payment": "all",
            "reject_invoice": "all",
            "export_pdf": "all",
            "view_attachment": "all",
            "export_cancelled": "all",
            "zatca_generate_xml": "all",
            "edit_template": "all",
            "zatca_export_xml": "all",
            "zatca_monitor": "all",
            "zatca_generate_qr": "all",
            "zatca_settings": "all",
            "delete_approved": "all",
            "issue_invoice": "all",
            "add_invoice": "all",
            "delete_paid": "all",
            "edit_approved_invoice": "all",
            "preview_invoice": "all",
            "view_table": "all",
            "unapprove_invoice": "all",
            "view_portal": "all",
            "zatca_view_log": "all",
            "edit_amount": "all",
            "zatca_send": "all",
            "export_all": "all",
            "edit_tax_data": "all",
            "edit_items": "all",
            "edit_before_approval": "all",
            "modify_qr": "all",
            "edit_attachment": "all",
            "edit_pending": "all",
            "edit_due_date": "all",
            "edit_discount": "all",
            "upload_receipt": "all"
          },
          "supplier_invoices": {
            "view_qr": "all",
            "send_approval": "all",
            "view_details": "all",
            "view_portal": "all",
            "edit_payment": "all",
            "search_invoices": "all",
            "edit_vat": "all",
            "edit_recorded": "all",
            "unapprove_paid": "all",
            "edit_amount": "all",
            "cancel_invoice": "all",
            "open_add_modal": "all",
            "export_all": "all",
            "edit_items": "all",
            "edit_before_approval": "all",
            "edit_invoice": "all",
            "approve_invoice": "all",
            "use_filters": "all",
            "create_from_po": "all",
            "request_revision": "all",
            "edit_attachment": "all",
            "edit_pending": "all",
            "edit_paid_amount": "all",
            "delete_unapproved": "all",
            "edit_due_date": "all",
            "print_invoice": "all",
            "edit_discount": "all",
            "upload_receipt": "all",
            "edit_approved": "all",
            "pay_unapproved": "all",
            "register_payment": "all",
            "upload_attachment": "all",
            "view_log": "all",
            "export_pdf": "all",
            "reject_invoice": "all",
            "view_attachment": "all",
            "delete_approved_attachment": "all",
            "delete_recorded": "all",
            "delete_payment": "all",
            "delete_approved": "all",
            "save_recorded": "all",
            "add_invoice": "all",
            "edit_approved_invoice": "all",
            "delete_paid": "all",
            "preview_invoice": "all",
            "view_table": "all",
            "link_payment_account": "all",
            "unapprove_invoice": "all"
          },
          "revenues": {
            "view_revenues": "all",
            "edit_revenues": "all"
          },
          "zatca": {
            "view_zatca": "all",
            "edit_zatca": "all"
          },
          "journal": {
            "approve_entry": "all",
            "view_projects": "all",
            "add_entry": "all",
            "edit_entry": "all",
            "print_entry": "all",
            "view_entries": "all",
            "submit_approval": "all",
            "upload_attachment": "all"
          },
          "cash_bank": {
            "add_transfer": "all",
            "view_dashboard": "all",
            "approve_transfer": "all",
            "view_portal": "all",
            "edit_transaction": "all",
            "delete_transaction": "all",
            "manage_cash_boxes": "all",
            "manage_bank_accounts": "all",
            "view_archive": "all",
            "manage_reconciliation": "all",
            "add_transaction": "all",
            "approve_transaction": "all",
            "view_audit_log": "all"
          },
          "expenses": {
            "view_expenses": "all",
            "edit_expenses": "all"
          },
          "payroll": {
            "audit_payroll_view": "all",
            "edit_payroll": "all",
            "revert_to_draft": "all",
            "view_payroll": "all",
            "audit_payroll_edit": "all"
          },
          "reports": {
            "export_reports": "all",
            "view_reports": "all"
          },
          "dashboard": {
            "edit_dashboard": "all",
            "view_dashboard": "all"
          }
        }
      },
      "moduleAccess": {
        "notifications": {
          "editAccess": "all",
          "enabled": true,
          "deleteAccess": "all",
          "viewAccess": "all"
        },
        "production": {
          "deleteAccess": "all",
          "enabled": true,
          "editAccess": "all",
          "viewAccess": "all"
        },
        "hr": {
          "deleteAccess": "all",
          "enabled": true,
          "editAccess": "all",
          "viewAccess": "all"
        },
        "procurement": {
          "viewAccess": "all",
          "enabled": true,
          "deleteAccess": "all",
          "editAccess": "all"
        },
        "finance": {
          "enabled": true,
          "deleteAccess": "all",
          "editAccess": "all",
          "viewAccess": "all"
        },
        "sales": {
          "enabled": true,
          "deleteAccess": "all",
          "editAccess": "all",
          "viewAccess": "all"
        }
      },
      "scopes": {
        "global": "all"
      },
      "boundDeviceName": ""
    },
    "password": "2424",
    "is_super_admin": true,
    "empId": "EMP-7300",
    "role": "Super Admin",
    "jobTitle": "اخصائي ادارة مشاريع",
    "allowDeviceMigration": true
  },
  {
    "username": "IBRAHIM",
    "email": "ibrahim@alwaleed-factory.com",
    "id": "IBRAHIM",
    "permissions": {
      "advanced": {
        "sales": {
          "prod_orders": {
            "resend_prod": "own",
            "delete_prod_order": "own",
            "view_prod_orders": "own"
          },
          "letters": {
            "add_letter": "own",
            "view_letters": "own",
            "send_letter": "own"
          },
          "collection": {
            "edit_plan": "own",
            "delete_payment": "own",
            "add_plan": "own",
            "view_collection": "own",
            "add_payment": "own"
          },
          "quotations": {
            "edit_quote": "own",
            "send_production": "own",
            "view_quotes": "own",
            "add_quote": "own"
          },
          "clients": {
            "edit_client": "own",
            "view_clients": "own",
            "add_client": "own",
            "delete_client": false,
            "import_clients": "all"
          },
          "reports": {
            "export_reports": false,
            "view_reports": false
          },
          "dashboard": {
            "view_dashboard": "own",
            "view_financial": "own"
          }
        },
        "production": {
          "orders": {
            "view_orders": "all",
            "approve_orders": "all",
            "manage_orders": "all"
          },
          "daily_followup": {
            "edit_daily_followup": "all",
            "view_daily_followup": "all",
            "manage_daily_followup": "all"
          },
          "projects": {
            "view_projects": "all",
            "mark_ready": "all",
            "mark_complete_no_auth": "all",
            "manage_stages": "all"
          },
          "installation": {
            "schedule_install": "all",
            "view_install": "all",
            "complete_install": "all"
          },
          "received": {
            "accept_reject": "all",
            "create_order": "all",
            "view_received": "all",
            "view_cost_pricing": "all"
          },
          "dashboard": {
            "view_dashboard": "all"
          }
        },
        "procurement": {
          "dashboard": {
            "view_dashboard": false
          }
        }
      },
      "moduleAccess": {
        "sales": {
          "enabled": true,
          "viewCosts": false,
          "view": true,
          "approve": false,
          "editAccess": "all",
          "edit": false,
          "viewAccess": "all",
          "deleteAccess": "own",
          "add": true,
          "deleteSensitive": false,
          "exportExcel": true,
          "print": true,
          "delete": false,
          "exportPdf": true
        },
        "reports": {
          "exportPdf": false,
          "delete": false,
          "print": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "deleteAccess": "own",
          "add": false,
          "viewAccess": "own",
          "editAccess": "own",
          "edit": false,
          "approve": false,
          "view": true,
          "viewCosts": false,
          "enabled": false
        },
        "procurement": {
          "enabled": false,
          "viewCosts": false,
          "edit": false,
          "editAccess": "none",
          "approve": false,
          "view": true,
          "add": false,
          "viewAccess": "none",
          "exportPdf": false,
          "delete": false,
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false
        },
        "hr": {
          "delete": false,
          "exportPdf": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "print": false,
          "add": false,
          "viewAccess": "none",
          "edit": false,
          "editAccess": "none",
          "view": true,
          "approve": false,
          "viewCosts": false,
          "enabled": false
        },
        "production": {
          "exportPdf": true,
          "delete": true,
          "print": true,
          "exportExcel": true,
          "deleteSensitive": false,
          "deleteAccess": "all",
          "add": true,
          "viewAccess": "all",
          "edit": true,
          "editAccess": "all",
          "approve": false,
          "view": true,
          "enabled": true,
          "viewCosts": true
        },
        "finance": {
          "exportPdf": true,
          "delete": false,
          "print": true,
          "exportExcel": true,
          "deleteSensitive": false,
          "add": true,
          "deleteAccess": "own",
          "viewAccess": "own",
          "edit": false,
          "editAccess": "own",
          "approve": false,
          "view": true,
          "enabled": true,
          "viewCosts": false
        },
        "settings": {
          "view": true,
          "deleteSensitive": false,
          "exportExcel": false,
          "print": false,
          "approve": false,
          "delete": false,
          "edit": false,
          "exportPdf": false,
          "viewCosts": false,
          "enabled": false,
          "add": false
        }
      },
      "scopes": {
        "global": "all"
      }
    },
    "password": "1969",
    "empId": "EMP-4359",
    "role": "Production",
    "jobTitle": "مشرف انتاج"
  },
  {
    "username": "MUSA",
    "email": "musa@alwaleed-factory.com",
    "id": "MUSA",
    "jobTitle": "مسؤول مشتريات ومستودع",
    "role": "Purchasing",
    "empId": "EMP-9738",
    "password": "1991",
    "permissions": {
      "advanced": {
        "procurement": {
          "approved_po": {
            "cancel_po": false,
            "view_pos": true,
            "receive_items": true
          },
          "requests": {
            "view_requests": true,
            "send_pricing": true,
            "add_request": true
          },
          "materials": {
            "manage_materials": true,
            "adjust_qty": true,
            "view_materials": true
          },
          "dashboard": {
            "view_dashboard": "all"
          },
          "items": {
            "manage_items": true,
            "approve_item": true,
            "view_items": true
          },
          "suppliers": {
            "manage_suppliers": "all",
            "issue_rfq": "all",
            "view_suppliers": "all"
          },
          "finance_approval": {
            "reject_finance_po": false,
            "approve_finance_po": false,
            "undo_po": false,
            "view_finance_po": false
          }
        }
      },
      "moduleAccess": {
        "reports": {
          "viewAccess": "own",
          "add": true,
          "deleteAccess": "own",
          "print": true,
          "exportExcel": true,
          "deleteSensitive": false,
          "exportPdf": true,
          "delete": false,
          "enabled": true,
          "viewCosts": false,
          "approve": false,
          "view": true,
          "edit": false,
          "editAccess": "own"
        },
        "sales": {
          "exportPdf": false,
          "delete": false,
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "add": false,
          "viewAccess": "none",
          "editAccess": "none",
          "edit": false,
          "approve": false,
          "view": true,
          "viewCosts": false,
          "enabled": false
        },
        "settings": {
          "add": false,
          "enabled": false,
          "viewCosts": false,
          "exportPdf": false,
          "edit": false,
          "delete": false,
          "approve": false,
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "view": true
        },
        "finance": {
          "delete": false,
          "exportPdf": false,
          "edit": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "view": true,
          "approve": false,
          "print": false,
          "add": false,
          "viewCosts": false,
          "enabled": false
        },
        "hr": {
          "viewAccess": "none",
          "add": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "print": false,
          "delete": false,
          "exportPdf": false,
          "enabled": false,
          "viewCosts": false,
          "view": true,
          "approve": false,
          "editAccess": "none",
          "edit": false
        },
        "production": {
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "exportPdf": false,
          "delete": false,
          "viewAccess": "none",
          "add": false,
          "approve": false,
          "view": true,
          "editAccess": "none",
          "edit": false,
          "enabled": false,
          "viewCosts": false
        },
        "procurement": {
          "exportPdf": true,
          "delete": true,
          "print": true,
          "exportExcel": true,
          "deleteSensitive": false,
          "add": true,
          "deleteAccess": "all",
          "viewAccess": "all",
          "edit": true,
          "editAccess": "all",
          "approve": false,
          "view": true,
          "enabled": true,
          "viewCosts": true
        }
      },
      "scopes": {
        "global": "all"
      }
    }
  },
  {
    "username": "SAMA7",
    "email": "sama7@alwaleed-factory.com",
    "id": "SAMA7",
    "createdAt": "2026-07-09T07:42:08.871Z",
    "jobTitle": "SOP",
    "department": "",
    "role": "Employee",
    "empId": "EMP-7113",
    "status": "active",
    "password": "1979",
    "permissions": {
      "moduleAccess": {
        "reports": {
          "add": false,
          "deleteAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "viewAccess": "none",
          "exportPdf": false,
          "editAccess": "none",
          "print": false,
          "approve": false,
          "exportExcel": false,
          "deleteSensitive": false
        },
        "sales": {
          "deleteAccess": "none",
          "add": false,
          "enabled": false,
          "viewCosts": false,
          "viewAccess": "none",
          "exportPdf": false,
          "editAccess": "none",
          "print": false,
          "approve": false,
          "exportExcel": false,
          "deleteSensitive": false
        },
        "finance": {
          "viewAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "deleteAccess": "none",
          "add": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "approve": false,
          "print": false,
          "exportPdf": false,
          "editAccess": "none"
        },
        "settings": {
          "deleteAccess": "none",
          "add": false,
          "viewCosts": false,
          "enabled": false,
          "viewAccess": "none",
          "exportPdf": false,
          "editAccess": "none",
          "approve": false,
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false
        },
        "notifications": {
          "exportExcel": false,
          "deleteSensitive": false,
          "approve": false,
          "print": false,
          "editAccess": "none",
          "exportPdf": false,
          "viewAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "add": false,
          "deleteAccess": "none"
        },
        "procurement": {
          "deleteAccess": "none",
          "add": false,
          "viewAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "editAccess": "none",
          "exportPdf": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "print": false,
          "approve": false
        },
        "production": {
          "approve": false,
          "print": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "exportPdf": false,
          "editAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "viewAccess": "none",
          "add": false,
          "deleteAccess": "none"
        },
        "hr": {
          "deleteAccess": "none",
          "add": false,
          "viewCosts": false,
          "enabled": false,
          "viewAccess": "none",
          "editAccess": "none",
          "exportPdf": false,
          "print": false,
          "approve": false,
          "exportExcel": false,
          "deleteSensitive": false
        }
      },
      "scopes": {
        "global": "all"
      },
      "advanced": {
        "procurement": {
          "dashboard": {
            "view_dashboard": false
          }
        }
      }
    },
    "createdBy": "FERAS",
    "name": ""
  },
  {
    "username": "SHARIF",
    "email": "sharif@alwaleed-factory.com",
    "id": "SHARIF",
    "jobTitle": "مندوب دعاية واعلان",
    "role": "Sales Rep",
    "empId": "EMP-9378",
    "password": "1982",
    "permissions": {
      "moduleAccess": {
        "production": {
          "viewAccess": "all",
          "add": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "print": false,
          "delete": false,
          "exportPdf": false,
          "viewCosts": false,
          "enabled": true,
          "view": true,
          "approve": false,
          "edit": false,
          "editAccess": "all"
        },
        "hr": {
          "view": true,
          "approve": false,
          "edit": false,
          "editAccess": "none",
          "viewCosts": false,
          "enabled": false,
          "exportExcel": false,
          "deleteSensitive": false,
          "print": false,
          "delete": false,
          "exportPdf": false,
          "viewAccess": "none",
          "add": false
        },
        "procurement": {
          "exportExcel": false,
          "deleteSensitive": false,
          "print": false,
          "delete": false,
          "exportPdf": false,
          "viewAccess": "all",
          "add": false,
          "view": true,
          "approve": false,
          "edit": false,
          "editAccess": "all",
          "viewCosts": false,
          "enabled": true
        },
        "finance": {
          "delete": true,
          "exportPdf": true,
          "exportExcel": true,
          "deleteSensitive": false,
          "print": true,
          "add": true,
          "deleteAccess": "own",
          "viewAccess": "own",
          "edit": true,
          "editAccess": "own",
          "view": true,
          "approve": false,
          "viewCosts": false,
          "enabled": true
        },
        "settings": {
          "enabled": false,
          "viewCosts": false,
          "add": false,
          "deleteSensitive": false,
          "exportExcel": false,
          "view": true,
          "approve": false,
          "print": false,
          "delete": false,
          "exportPdf": false,
          "edit": false
        },
        "sales": {
          "edit": true,
          "editAccess": "all",
          "approve": false,
          "view": true,
          "enabled": true,
          "viewCosts": false,
          "exportPdf": true,
          "delete": true,
          "print": true,
          "deleteSensitive": false,
          "exportExcel": true,
          "add": true,
          "deleteAccess": "own",
          "viewAccess": "all"
        },
        "reports": {
          "approve": false,
          "print": false,
          "view": true,
          "exportExcel": false,
          "deleteSensitive": false,
          "edit": false,
          "exportPdf": false,
          "delete": false,
          "enabled": true,
          "viewCosts": false,
          "add": false
        }
      },
      "scopes": {
        "global": "all"
      },
      "advanced": {
        "dashboard": {
          "metrics": {
            "view_main": false,
            "view_sales": false
          }
        },
        "production": {
          "dashboard": {
            "view_dashboard": "all"
          },
          "projects": {
            "view_projects": "all"
          },
          "installation": {
            "view_install": "all"
          }
        },
        "sales": {
          "reports": {
            "export_reports": false,
            "view_reports": "own"
          },
          "dashboard": {
            "view_dashboard": "own",
            "view_financial": "own"
          },
          "clients": {
            "edit_client": "all",
            "view_clients": true,
            "import_clients": true,
            "delete_client": "own",
            "add_client": true
          },
          "quotations": {
            "add_quote": "own",
            "send_production": "own",
            "edit_quote": "own",
            "unapprove_quote": false,
            "delete_approved_quote": false,
            "view_quotes": "own",
            "delete_quote": false,
            "approve_quote": false
          },
          "prod_orders": {
            "resend_prod": "own",
            "view_prod_orders": "all"
          },
          "letters": {
            "send_letter": "own",
            "view_letters": "own",
            "add_letter": "own"
          },
          "collection": {
            "delete_payment": "own",
            "add_plan": "own",
            "edit_plan": "own",
            "approve_payment": "own",
            "view_collection": "own",
            "add_payment": "own"
          }
        },
        "procurement": {
          "items": {
            "manage_items": "all",
            "approve_item": "all",
            "view_items": "all"
          },
          "dashboard": {
            "view_dashboard": false
          }
        }
      }
    }
  }
];
